# Generated by Django 4.2.18 on 2025-02-05 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_alter_tag_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPUTER_STATUS", "Computer Status"),
                            ("FILE_SCAN", "File Scan"),
                            ("FILE_ACCESS", "File Access"),
                            ("SYSTEM", "System"),
                            ("AUTH", "Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("COMPUTER_ONLINE", "Computer Online"),
                            ("COMPUTER_OFFLINE", "Computer Offline"),
                            ("COMPUTER_REGISTERED", "Computer Registered"),
                            ("COMPUTER_UPDATED", "Computer Updated"),
                            ("SCAN_STARTED", "Scan Started"),
                            ("SCAN_COMPLETED", "Scan Completed"),
                            ("SCAN_ERROR", "Scan Error"),
                            ("FILE_FOUND", "File Found"),
                            ("FILE_INDEXED", "File Indexed"),
                            ("FILE_MODIFIED", "File Modified"),
                            ("FILE_DELETED", "File Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "computer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user_management.computer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["category", "event"],
                        name="user_manage_categor_86d140_idx",
                    ),
                    models.Index(
                        fields=["computer", "category"],
                        name="user_manage_compute_4be90a_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "level"],
                        name="user_manage_timesta_7d293b_idx",
                    ),
                ],
            },
        ),
    ]
