# Generated by Django 4.2.18 on 2025-03-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0003_computer_logged_in_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="computer",
            options={"ordering": ["label"]},
        ),
        migrations.RemoveField(
            model_name="computer",
            name="disk_usage_percent",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="failed_transfers",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="last_transfer",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="password",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="successful_transfers",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="total_bytes_transferred",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="total_transfers",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="user_profile",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="username",
        ),
        migrations.AddField(
            model_name="computer",
            name="boot_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="cpu_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="cpu_frequency_current",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="cpu_frequency_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="cpu_frequency_min",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="cpu_physical_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="disk_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="memory_available",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="memory_total",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="memory_used",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="network_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="hostname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ip_address",
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name="computer",
            table=None,
        ),
    ]
