# Generated by Django 4.2.18 on 2025-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0004_systemlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_password_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
