# Generated by Django 4.2.18 on 2025-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0005_customuser_last_password_change"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="schedule_type",
            field=models.CharField(
                choices=[
                    ("I", "Immediate"),
                    ("H", "Hourly"),
                    ("D", "Daily"),
                    ("W", "Weekly"),
                    ("M", "Monthly"),
                ],
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="LogAggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("HOUR", "Hourly"),
                            ("DAY", "Daily"),
                            ("WEEK", "Weekly"),
                            ("MONTH", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPUTER_STATUS", "Computer Status"),
                            ("FILE_SCAN", "File Scan"),
                            ("FILE_ACCESS", "File Access"),
                            ("SYSTEM", "System"),
                            ("AUTH", "Authentication"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("COMPUTER_ONLINE", "Computer Online"),
                            ("COMPUTER_OFFLINE", "Computer Offline"),
                            ("COMPUTER_REGISTERED", "Computer Registered"),
                            ("COMPUTER_UPDATED", "Computer Updated"),
                            ("SCAN_STARTED", "Scan Started"),
                            ("SCAN_COMPLETED", "Scan Completed"),
                            ("SCAN_ERROR", "Scan Error"),
                            ("FILE_FOUND", "File Found"),
                            ("FILE_INDEXED", "File Indexed"),
                            ("FILE_MODIFIED", "File Modified"),
                            ("FILE_DELETED", "File Deleted"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("DEBUG", "Debug"),
                        ],
                        max_length=10,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("warning_count", models.IntegerField(default=0)),
                ("unique_users", models.IntegerField(default=0)),
                ("unique_computers", models.IntegerField(default=0)),
                ("most_common_message", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-start_time", "category"],
                "indexes": [
                    models.Index(
                        fields=["period", "start_time"],
                        name="user_manage_period_457201_idx",
                    ),
                    models.Index(
                        fields=["category", "event"],
                        name="user_manage_categor_591f8e_idx",
                    ),
                    models.Index(fields=["level"], name="user_manage_level_e399bb_idx"),
                ],
            },
        ),
    ]
