# Generated by Django 4.2.18 on 2025-03-17 17:15

from django.db import migrations


class Migration(migrations.Migration):
    """
    Clean up metric fields and ensure we're using the metrics JSONField.
    All computer metrics (CPU, memory, disk) are now stored in the metrics JSONField.
    """

    dependencies = [
        ('user_management', '0005_computer_system_metrics'),
    ]

    operations = [
        # No operations needed - the fields we thought existed don't actually exist
        # All metrics are already being stored in the metrics JSONField
    ]
