# Generated by Django 4.2.18 on 2025-03-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0006_cleanup_metrics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='model',
        ),
        migrations.AddField(
            model_name='computer',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='disk_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='memory_usage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='disk_total',
            new_name='total_disk',
        ),
    ]
