# Generated by Django 4.2.18 on 2025-02-06 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0006_alter_schedule_schedule_type_logaggregation"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "pattern_type",
                    models.CharField(
                        choices=[
                            ("SEQUENCE", "Event Sequence"),
                            ("THRESHOLD", "Threshold Based"),
                            ("CORRELATION", "Event Correlation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(help_text="JSON defining the pattern conditions"),
                ),
                ("alert_threshold", models.IntegerField(default=1)),
                ("cooldown_minutes", models.IntegerField(default=60)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_triggered", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="LogAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField()),
                ("acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_logs",
                    models.ManyToManyField(to="user_management.systemlog"),
                ),
                (
                    "pattern",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_management.logpattern",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogCorrelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correlation_id", models.UUIDField(default=uuid.uuid4)),
                ("correlation_type", models.CharField(max_length=50)),
                ("confidence_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "primary_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="primary_correlations",
                        to="user_management.systemlog",
                    ),
                ),
                (
                    "related_logs",
                    models.ManyToManyField(
                        related_name="related_correlations",
                        to="user_management.systemlog",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["correlation_id"], name="user_manage_correla_a92aa7_idx"
                    ),
                    models.Index(
                        fields=["correlation_type"],
                        name="user_manage_correla_cc4ffe_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="user_manage_created_1c031a_idx"
                    ),
                ],
            },
        ),
    ]
