# Generated by Django 4.2.18 on 2025-02-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0007_logpattern_logalert_logcorrelation"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("PENDING", "Pending"),
                    ("RESOLVED", "Resolved"),
                    ("OVERDUE", "Overdue"),
                ],
                default="OPEN",
                max_length=20,
            ),
        ),
    ]
