# Generated by Django 4.2.18 on 2025-03-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0007_auto_20250318_1206"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="computer",
            name="cpu_architecture",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="cpu_speed",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="disk_free",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="disk_info",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="disk_used",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="memory_available",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="memory_total",
        ),
        migrations.RemoveField(
            model_name="computer",
            name="memory_used",
        ),
        migrations.AddField(
            model_name="computer",
            name="metrics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="computer",
            name="total_memory",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="label",
            field=models.CharField(max_length=255),
        ),
    ]
