# Generated by Django 4.2.18 on 2025-02-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0008_systemlog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
