# Generated by Django 4.2.18 on 2025-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0008_remove_computer_cpu_architecture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="memory_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="cpu_percent",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="computer",
            name="disk_percent",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
