# Generated by Django 4.2.18 on 2025-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_add_percent_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="computer",
            name="manufacturer",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="device_class",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="hostname",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="logged_in_user",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="metrics",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="computer",
            name="os_version",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
