# Generated by Django 4.2.18 on 2025-02-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0009_notification_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "selected_days",
                    models.JSONField(
                        blank=True,
                        help_text="List of days for weekly schedule (0-6)",
                        null=True,
                    ),
                ),
                (
                    "monthly_date",
                    models.IntegerField(
                        blank=True,
                        help_text="Day of month for monthly schedule (1-31)",
                        null=True,
                    ),
                ),
                ("email_notification", models.BooleanField(default=False)),
                (
                    "email_addresses",
                    models.JSONField(
                        default=list,
                        help_text="List of email addresses for notifications",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                (
                    "computers",
                    models.ManyToManyField(
                        related_name="scan_schedules", to="user_management.computer"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scan Schedule",
                "verbose_name_plural": "Scan Schedules",
                "ordering": ["created_at"],
            },
        ),
    ]
