# Generated by Django 4.2.18 on 2025-02-19 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0010_scanschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanschedule",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="email_addresses",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="email_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="monthly_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="selected_days",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scanschedule",
            name="type",
            field=models.CharField(
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=20,
            ),
        ),
    ]
