# Generated by Django 4.2.18 on 2025-02-19 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "user_management",
            "0011_scanschedule_user_alter_scanschedule_email_addresses_and_more",
        ),
    ]

    operations = []
