# Generated by Django 4.2.18 on 2025-02-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="computer_offline_threshold",
            field=models.IntegerField(
                default=10, help_text="Minutes before sending offline notification"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_computer_offline",
            field=models.BooleanField(
                default=True, help_text="Notify when computers go offline"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_pdf_errors",
            field=models.BooleanField(
                default=True, help_text="Notify when PDF copy/processing errors occur"
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="notify_scan_errors",
            field=models.BooleanField(
                default=True, help_text="Notify when scanning errors occur"
            ),
        ),
    ]
