# Generated by Django 4.2.18 on 2025-02-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_pdfattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
